export const UPDATE_CONTENT = "UPDATE_CONTENT";

export const SET_LOADING = "SET_LOADING";
export const CHANGE_THEME = "CHANGE_THEME";
export const CHANGE_LANGUAGE = "CHANGE_LANGUAGE";

export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const UPDATE_CURRENT_ID = "UPDATE_CURRENT_ID";
export const CLEAN_CURRENT_USER = "CLEAN_CURRENT_USER";
export const UPDATE_USERS = "UPDATE_USERS";
export const REMOVE_USER = "REMOVE_USER";
